services:
  - type: web
    name: cuisine-craft
    env: python
    buildCommand: "./build.sh"
    startCommand: "cd backend && gunicorn cuisine_craft_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cuisine-craft-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: RENDER
        value: true
      - key: PYTHON_VERSION
        value: 3.11.0

databases:
  - name: cuisine-craft-db
    databaseName: cuisine_craft
    user: cuisine_craft_user
    plan: free 