services:
  - type: web
    name: cuisine-craft
    env: python
    buildCommand: "./build.sh"
    startCommand: "cd backend && gunicorn cuisine_craft_project.wsgi:application --bind 0.0.0.0:$PORT"
    plan: starter
    healthCheckPath: /api/recipes/
    buildFilter:
      paths:
        - backend/**
        - frontend/**
        - build.sh
        - requirements.txt
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cuisine-craft-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: RENDER
        value: true
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: "True"
      - key: IMPORT_TIMEOUT
        value: 600

databases:
  - name: cuisine-craft-db
    databaseName: cuisine_craft
    user: cuisine_craft_user
    plan: free