# Generated by Django 5.1.6 on 2025-03-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipeingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
