# Generated by Django 5.1.6 on 2025-03-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image_name',
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
