# Generated by Django 5.1.6 on 2025-03-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_recipe_image_name_recipe_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='measurement',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
